name: docs

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: compas-dev/compas-actions.docs@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
